labelst_part_path: "/fanxiangssd/yaroslav/projects/002_green_data/004_leaves_seg/labeling/004_022_photo/LS_jsons/1_Zdorovyi/labels"
pth_imgs: "/fanxiangssd/yaroslav/projects/002_green_data/004_leaves_seg/labeling/004_022_photo/003_022_002_labelled_26_10_24/1_Zdorovyi"

# weight_model: "/Users/YaVolkonskiy/Documents/Projects/tomato/data/002_data_experiments/002_train_leaf_tomato/10_11_2023/best_leaf.pt"
weight_model : "/fanxiangssd/yaroslav/projects/002_green_data/004_leaves_seg/001_train/001_exp/results/train2/weights/best.pt"

file_label_studio: "/fanxiangssd/yaroslav/projects/002_green_data/004_leaves_seg/labeling/004_022_photo/LS_jsons/1_Zdorovyi/1_Zdorovyi.json"